server_port: 8080
dsn: "host=postgres user=postgres password=changeme dbname=postgres port=5432 sslmode=disable TimeZone=Asia/Shanghai"
jwt_signing_key: "LxsKJywDL5O5PvgODZhBH12KE6k2yL8E"
jwt_expiration: 3600