package auth

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/http/httptest"
	"testing"

	respErrors "code-challenge/internal/errors"
	"code-challenge/pkg/log"

	"github.com/gin-gonic/gin"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/mock"
)

func TestHandler_Register(t *testing.T) {
	gin.SetMode(gin.TestMode)
	t.Run("Login success", func(t *testing.T) {
		mockService := new(MockService)
		logger := log.New()
		ctx := context.Background()
		handler := NewHandler(mockService, logger)
		r := SetUpRouter()
		r.POST("/login", handler.Login)

		mockService.On("Authenticate", ctx, mock.Anything, mock.Anything).Return("test_token", nil)
		mockCredentials := Credentials{
			Username: "test",
			Password: "123",
		}

		jsonValue, _ := json.Marshal(mockCredentials)
		request, _ := http.NewRequest(http.MethodPost, "/login", bytes.NewBuffer(jsonValue))

		w := httptest.NewRecorder()
		r.ServeHTTP(w, request)

		assert.Equal(t, 200, w.Code)
		expectedResp := map[string]string{"token": "test_token"}
		var actualResp map[string]string
		_ = json.Unmarshal(w.Body.Bytes(), &actualResp)
		assert.Equalf(t, expectedResp, actualResp, "expected: %v, actual: %v", expectedResp, actualResp)

		mockService.AssertExpectations(t)
	})

	t.Run("Login fails, empty username/password", func(t *testing.T) {
		mockService := new(MockService)
		logger := log.New()
		handler := NewHandler(mockService, logger)
		r := SetUpRouter()
		r.POST("/login", handler.Login)

		mockCredentials := Credentials{
			Username: "",
			Password: "",
		}

		jsonValue, _ := json.Marshal(mockCredentials)
		request, _ := http.NewRequest(http.MethodPost, "/login", bytes.NewBuffer(jsonValue))

		w := httptest.NewRecorder()
		r.ServeHTTP(w, request)

		assert.Equal(t, 400, w.Code)

		mockService.AssertExpectations(t)
	})

	t.Run("Login fails, internal error from service", func(t *testing.T) {
		mockService := new(MockService)
		logger := log.New()
		ctx := context.Background()
		handler := NewHandler(mockService, logger)
		r := SetUpRouter()
		r.POST("/login", handler.Login)

		mockService.On("Authenticate", ctx, mock.Anything, mock.Anything).Return("", fmt.Errorf("mock error"))
		mockCredentials := Credentials{
			Username: "test",
			Password: "123",
		}

		jsonValue, _ := json.Marshal(mockCredentials)
		request, _ := http.NewRequest(http.MethodPost, "/login", bytes.NewBuffer(jsonValue))

		w := httptest.NewRecorder()
		r.ServeHTTP(w, request)

		assert.Equal(t, 500, w.Code)
		mockService.AssertExpectations(t)
	})

	t.Run("Login fails, incorrect username/password", func(t *testing.T) {
		mockService := new(MockService)
		logger := log.New()
		ctx := context.Background()
		handler := NewHandler(mockService, logger)
		r := SetUpRouter()
		r.POST("/login", handler.Login)

		mockService.On("Authenticate", ctx, mock.Anything, mock.Anything).Return("", respErrors.BadRequest("incorrect username/password"))
		mockCredentials := Credentials{
			Username: "test",
			Password: "123",
		}

		jsonValue, _ := json.Marshal(mockCredentials)
		request, _ := http.NewRequest(http.MethodPost, "/login", bytes.NewBuffer(jsonValue))

		w := httptest.NewRecorder()
		r.ServeHTTP(w, request)

		assert.Equal(t, 400, w.Code)

		mockService.AssertExpectations(t)
	})
}

func SetUpRouter() *gin.Engine {
	router := gin.Default()
	return router
}

// MockService is an autogenerated mock type for the service type
type MockService struct {
	mock.Mock
}

// Authenticate provides a mock function with given fields: ctx, username, password
func (_m *MockService) Authenticate(ctx context.Context, username string, password string) (string, error) {
	ret := _m.Called(ctx, username, password)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, username, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, username, password)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, username, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
