package user

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/http/httptest"
	"testing"

	"code-challenge/internal/entity"
	respErrors "code-challenge/internal/errors"
	"code-challenge/pkg/log"

	"github.com/gin-gonic/gin"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/mock"
)

func TestHandler_Register(t *testing.T) {
	gin.SetMode(gin.TestMode)
	t.Run("Register success", func(t *testing.T) {
		mockService := new(MockService)
		logger := log.New()
		ctx := context.Background()
		handler := NewHandler(mockService, logger)
		r := SetUpRouter()
		r.POST("/register", handler.Register)

		mockService.On("Register", ctx, mock.Anything).Return("100", nil)
		mockRegisterRequest := RegisterRequest{
			Username: "test",
			Password: "123",
		}

		jsonValue, _ := json.Marshal(mockRegisterRequest)
		request, _ := http.NewRequest(http.MethodPost, "/register", bytes.NewBuffer(jsonValue))

		w := httptest.NewRecorder()
		r.ServeHTTP(w, request)

		assert.Equal(t, 201, w.Code)
		expectedResp := RegisterResponse{
			ID: "100",
		}
		var actualResp RegisterResponse
		_ = json.Unmarshal(w.Body.Bytes(), &actualResp)
		assert.Equalf(t, expectedResp, actualResp, "expected: %v, actual: %v", expectedResp, actualResp)

		mockService.AssertExpectations(t)
	})

	t.Run("Register user with empty username/password", func(t *testing.T) {
		mockService := new(MockService)
		logger := log.New()
		handler := NewHandler(mockService, logger)
		r := SetUpRouter()
		r.POST("/register", handler.Register)

		mockRegisterRequest := RegisterRequest{
			Username: "",
			Password: "",
		}

		jsonValue, _ := json.Marshal(mockRegisterRequest)
		request, _ := http.NewRequest(http.MethodPost, "/register", bytes.NewBuffer(jsonValue))

		w := httptest.NewRecorder()
		r.ServeHTTP(w, request)

		assert.Equal(t, 400, w.Code)
		mockService.AssertExpectations(t)
	})

	t.Run("Register user when there is a database connection problem", func(t *testing.T) {
		mockService := new(MockService)
		logger := log.New()
		ctx := context.Background()
		handler := NewHandler(mockService, logger)
		r := SetUpRouter()
		r.POST("/register", handler.Register)

		mockService.On("Register", ctx, mock.Anything).Return("", fmt.Errorf("mock error"))
		mockRegisterRequest := RegisterRequest{
			Username: "test",
			Password: "test",
		}

		jsonValue, _ := json.Marshal(mockRegisterRequest)
		request, _ := http.NewRequest(http.MethodPost, "/register", bytes.NewBuffer(jsonValue))

		w := httptest.NewRecorder()
		r.ServeHTTP(w, request)

		assert.Equal(t, 500, w.Code)
		mockService.AssertExpectations(t)
	})

	t.Run("Register user with internal error from service", func(t *testing.T) {
		mockService := new(MockService)
		logger := log.New()
		ctx := context.Background()
		handler := NewHandler(mockService, logger)
		r := SetUpRouter()
		r.POST("/register", handler.Register)

		mockService.On("Register", ctx, mock.Anything).Return("", respErrors.InternalServerError(""))
		mockRegisterRequest := RegisterRequest{
			Username: "test",
			Password: "test",
		}

		jsonValue, _ := json.Marshal(mockRegisterRequest)
		request, _ := http.NewRequest(http.MethodPost, "/register", bytes.NewBuffer(jsonValue))

		w := httptest.NewRecorder()
		r.ServeHTTP(w, request)

		assert.Equal(t, 500, w.Code)
		mockService.AssertExpectations(t)
	})
}

func SetUpRouter() *gin.Engine {
	router := gin.Default()
	return router
}

// MockService is an autogenerated mock type for the service type
type MockService struct {
	mock.Mock
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockService) GetByID(ctx context.Context, id string) (*entity.User, error) {
	ret := _m.Called(ctx, id)

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: ctx, req
func (_m *MockService) Register(ctx context.Context, req *RegisterRequest) (string, error) {
	ret := _m.Called(ctx, req)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *RegisterRequest) (string, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *RegisterRequest) string); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *RegisterRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
